### ISSUE TITLE
Idea: Dynamically mapping federated users

### ISSUE THREAD

**Issue by mumoshu** [heptiolabs/kubernetes-aws-authenticator#12]
@mattmoyer Hi, thanks for sharing the great project 👍 

Please let me share the idea came up to me today - I'd like SAML federated users to be mapped to correspondingly named K8S users created/updated on demand by kubernetes-aws-authenticator so that I could be released from statically mapping many IAM roles/users to k8s users.

I imagine that it would work similar to `mapEC2InstanceRoles` in regard to that [it also maps an EC2 instance id obtained by calling STS' `GetCallerIdentity` to the name of an automatically created k8s service account](https://github.com/heptiolabs/kubernetes-aws-authenticator/blob/ce71e0c60b43d9fec185b6a17cefe1b03941aefe/pkg/server/server.go#L190-L192).

Revisiting what we have so far - calling [GetCallerIdentity](http://docs.aws.amazon.com/cli/latest/reference/sts/get-caller-identity.html) within a session established via AssumeRoleWithSAML gives us:

```json
{
    "Account": "${account_id}",
    "UserId": "${unique_id_of_assumed_iam_role}:${caller_specified_role_name}",
    "Arn": "arn:aws:sts::${aws_account_id}:assumed-role/${assumed_iam_role_name}/${caller_specified_role_name}"
}
```

where:
- `unique_id_of_assumed_iam_role` is something like `AROAIUI*snip*R756ILNQ`, neither a role name nor a role arn.
- `caller_specified_role_name` can be anything specified by the ID provider but could be my e-mail address `mumoshu@example.com`

For example, given a `caller_specified_role_name` of `mumoshu@example.com`, I'd like kubernetes-aws-authenticator to automatically create or update the k8s service account `mumoshu` or `auto-mumoshu`, whichever doesn't collide with k8s users not managed by kubernetes-aws-authenticator.

I'd expect config to look like:

```yaml
mapFederatedUsers:
  - roleARN: arn:aws:iam::000000000000:role/Developer
    usernameFormat: adm-{{CallerSpecifiedRoleName}}
    groups:
    - developers
  - roleARN: arn:aws:iam::000000000000:role/Admin
    usernameFormat: dev-{{CallerSpecifiedRoleName}}
    groups:
    - admins
```

WDYT?

**Comment by mumoshu** [comment]
In case you've interested in trying a SAML-federated login to obtain a session used by awscli, I'd recommend OneLogin + https://github.com/physera/onelogin-aws-cli.

**Comment by mumoshu** [comment]
After reading [here](https://github.com/heptiolabs/kubernetes-aws-authenticator/blob/ce71e0c60b43d9fec185b6a17cefe1b03941aefe/pkg/token/token.go#L244-L245) and [there](https://github.com/heptiolabs/kubernetes-aws-authenticator/blob/ce71e0c60b43d9fec185b6a17cefe1b03941aefe/pkg/server/server.go#L191-L192) in the code base, I realized that in theory the following would work to achieve the same result as the above idea:

```yaml
mapEC2InstanceRoles:
  - roleARN: arn:aws:iam::000000000000:role/Developer
    usernameFormat: adm-{{InstanceID}}
    groups:
    - developers
  - roleARN: arn:aws:iam::000000000000:role/Admin
    usernameFormat: dev-{{InstanceID}}
    groups:
    - admins
```

Then, probably `mapEC2InstanceRoles` could be renamed to `mapAssumedRoles` which is more general to cover both cases? 🤔 

Also, as the result of `{{InstanceID}}` isn't really an instance ID for a assumed role, could we introduce something like `{{CallerSpecifiedRoleName}}` which is aliased to `{{InstanceID}}`?

// Btw, in case you wondered why I'd like to name it `CallerSpecifiedRoleName` which is not very intuitive, please refer to [the Principal table](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#principaltable) linked from [the reference page of get-caller-identity](http://docs.aws.amazon.com/cli/latest/reference/sts/get-caller-identity.html).
// The name is defined there.
